Testing client CI
mithril-security/bastionlab pull request #109
Opened 2022-12-07 09:28 UTC by theolebever

Description:

This PR adds a CI  pipeline to test the client side of BastionLab. The pipeline includes the following steps:

- Build and installation of the client
- Wait for the build of the server, download the artifact and launch the server through Docker
- Install the necessary dependencies for the testing of the client
- Testing with flake8 
- Testing with mypy
- Testing with pytest-cov
- Upload of the report made by pytest-cov

The benefits will be to no longer regress in the developpement of BastionLab client and automate the testing.

2022-12-07 10:25 UTC, JoFrost commented
Is the testing with Mypy necessary? Can't flake8 do what Mypy is doing?

2022-12-07 10:30 UTC, theolebever commented
> Is the testing with Mypy necessary? Can't flake8 do what Mypy is doing?

As I have understood, flake8 does more of a static analysis and mypy does more of a hybrid analysis. This CI was based on what has been done on BastionAI previously. But i can totally remove one of the tests if it is not necessary.

2022-12-07 10:56 UTC, JoFrost commented
> > Is the testing with Mypy necessary? Can't flake8 do what Mypy is doing?
> 
> As I have understood, flake8 does more of a static analysis and mypy does more of a hybrid analysis. This CI was based on what has been done on BastionAI previously. But i can totally remove one of the tests if it is not necessary.

Leave it as it is, it has its usefulness.
I was mostly curious about the approach of this test.

2023-01-04 16:31 UTC, dhalf requested changes

2023-01-04 16:31 UTC, dhalf commented on bastionai/client/tests/test_client.py
> +# from typing import Iterator
Why were these files commented out?

2023-01-04 16:31 UTC, dhalf commented on bastionai/examples/distilbert_example_notebook.ipynb
> +    "!pip install bastionlab"
Don't run examples from bastionai, there are not maintained.
Checking whether the notebooks in docs work is enough for now

2023-01-04 16:31 UTC, dhalf commented on docs/docs/how-to-guides/covid_cleaning_exploration.ipynb
> +   "metadata": {
Please double check that you don't introduce code changes in the documentation notebooks

2023-01-04 16:31 UTC, dhalf commented on examples/titanic.ipynb
> +   "execution_count": 59,
I guess this notebook is not maintained and can safely be removed

2023-01-04 16:31 UTC, dhalf commented on tests/server.py
> +# import errno
This file is commented, why?

2023-01-04 16:32 UTC, dhalf commented
Please resolve the conflicts with the documentation notebooks
The code MUST be the same as in master

2023-01-06 17:52 UTC, dhalf approved these changes

2023-01-06 17:54 UTC, merged