tutorial for updating policy and initial work on code
mithril-security/bastionlab pull request #164
Opened 2022-12-29 16:19 UTC by lyie28

-> tutorial added update_policy.ipynb
-> code added. Appears to be functional but requires cleaning up and testing

2023-01-02 10:39 UTC, dhalf requested changes
Could you move the update policy tutorial into the defining policy tutorial please?

2023-01-03 16:31 UTC, dhalf approved these changes

2023-01-04 15:55 UTC, dhalf requested changes

2023-01-04 15:55 UTC, dhalf commented on client/src/bastionlab/polars/remote_polars.py
> +    def update_policy(self, new_policy: Policy):
This is already inherited

2023-01-04 15:55 UTC, dhalf commented on server/bastionlab_polars/src/lib.rs
> +                    drop(dfs);
Consider using blocks instead of explicit drops

2023-01-06 12:46 UTC, ShannonSD commented
Please be aware that if authentication is disabled anyone can change policies making them useless. Maybe the logic should be to refuse alteration of policies when authentication is disabled.

2023-01-06 14:49 UTC, closed without merging