Savable rule 2
mithril-security/bastionlab pull request #165
Opened 2023-01-02 14:28 UTC by ShannonSD

Savable rule is now defined within the policy. The privacy policy notebook is updated as well.

This PR also fixes a typo error in the serialization of the AtLeastNOf rule and fixes a vulnerability in the way policies were inherited.

2023-01-02 16:32 UTC, dhalf requested changes

2023-01-02 16:32 UTC, dhalf commented on server/bastionlab_polars/src/serialization.rs
> +    println!("{}", policy);
Remove this

2023-01-02 16:41 UTC, ShannonSD commented on server/bastionlab_polars/src/serialization.rs
> +    println!("{}", policy);
Done

2023-01-03 14:13 UTC, dhalf approved these changes

2023-01-03 14:19 UTC, merged