Normalization
mithril-security/bastionlab pull request #178
Opened 2023-01-11 16:23 UTC by lyie28

Quick PoC for normalization idea

2023-01-18 10:42 UTC, dhalf requested changes

2023-01-18 10:42 UTC, dhalf commented on server/bastionlab_polars/src/composite_plan.rs
> +                        "Could not apply stack: no input data frame",
Change err message

2023-01-18 10:51 UTC, lyie28 commented on server/bastionlab_polars/src/composite_plan.rs
> +                        "Could not apply stack: no input data frame",
Oh yeah! Done :)

2023-01-26 16:09 UTC, dhalf approved these changes

2023-01-26 16:09 UTC, merged