fraud detection article
mithril-security/bastionlab pull request #200
Opened 2023-01-20 15:22 UTC by lyie28

fraud detection article

2023-01-20 17:06 UTC, lyie28 commented
Question for Ophelie: I interpreted this as the clients being victims of fraud. For example, they paid for a hotel online and the hotel didn't exist. But Daniel said maybe it is more that someone is pretending to be this client... It just makes a slight difference to some of the ways I explained my text, so we might need to change the text accordingly...

2023-01-26 10:38 UTC, dhalf reviewed
Please don't say recover the dataset as this might be understood as: "adversarially extract the dataset through the API in order to steal it or get private data from it"

2023-01-26 10:39 UTC, dhalf requested changes
Please don't say recover the dataset as this might be understood as: "adversarially extract the dataset through the API in order to steal it or get private data from it"

2023-01-26 13:38 UTC, dhalf approved these changes

2023-01-30 08:20 UTC, merged