better plan serialization
mithril-security/bastionlab pull request #219
Opened 2023-02-03 16:27 UTC by cchudant

This PR gets rid of the embarrassing (and cursed) way we used to serialize stuff to json

I've also started adding `__all__` to better control exports.
Things like `import bastionlab.convertor`, `import bastionlab.polars.utils` are still possible since they are files, and they end up in the public API and docs, which is kinda bad.

I'd like to move all the files in an `internals` folder, and have root module just be reexports. what do you think of that @dhalf?

2023-02-03 16:36 UTC, cchudant commented
I have a formatting problem, which i cannot reproduce locally
```sh
$ black client/src/bastionlab/polars/remote_polars.py --check
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```
but the CI flags this file as not well formatted

I am very confused, not sure what's wrong?

2023-02-09 09:40 UTC, dhalf requested changes

2023-02-09 09:40 UTC, dhalf commented on client/src/bastionlab/polars/policy.py
> +    pass
I don't think we need to subtype an abstract class anymore.
Instead, a uniform approach to use Unions everywhere would be to use a typevar equal to the union. This is event closer and truer to what enums are!

2023-02-09 12:56 UTC, cchudant commented
Fixed

2023-02-10 11:25 UTC, dhalf approved these changes

2023-02-10 16:21 UTC, dhalf approved these changes

2023-02-10 16:22 UTC, merged